CREATE TABLE IF NOT EXISTS marks (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_username VARCHAR(100) NOT NULL,
    subject_name     VARCHAR(100) NOT NULL,
    teacher_username VARCHAR(100) NOT NULL,
    score            INT          NOT NULL,
    full_marks       INT          NOT NULL DEFAULT 100,
    exam_type        VARCHAR(50)  NOT NULL DEFAULT 'Terminal',
    remarks          VARCHAR(255),
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
)
