CREATE TABLE IF NOT EXISTS attendance (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_username VARCHAR(100) NOT NULL,
    teacher_username VARCHAR(100) NOT NULL,
    subject_name     VARCHAR(100) NOT NULL,
    attendance_date  DATE         NOT NULL,
    status           VARCHAR(10)  NOT NULL DEFAULT 'PRESENT',
    CONSTRAINT uq_attendance UNIQUE (student_username, teacher_username, attendance_date, subject_name)
)
