package com.hammroschool.config;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public final class DatabaseSupport {
    private static final DatabaseSupport INSTANCE = new DatabaseSupport(AppConfig.getInstance());

    private final String databaseUrl;
    private final String databaseUsername;
    private final String databasePassword;
    private final String databaseDriver;
    private boolean initialized;

    DatabaseSupport(AppConfig appConfig) {
        this(appConfig.getDatabaseUrl(), appConfig.getDatabaseUsername(), appConfig.getDatabasePassword(), appConfig.getDatabaseDriver());
    }

    public DatabaseSupport(String databaseUrl, String databaseUsername, String databasePassword, String databaseDriver) {
        this.databaseUrl = databaseUrl;
        this.databaseUsername = databaseUsername;
        this.databasePassword = databasePassword;
        this.databaseDriver = databaseDriver;
    }

    public static DatabaseSupport getInstance() {
        return INSTANCE;
    }

    public synchronized Connection openConnection() throws SQLException {
        initializeSchemaIfNeeded();
        return DriverManager.getConnection(databaseUrl, databaseUsername, databasePassword);
    }

    public synchronized void initializeSchemaIfNeeded() {
        if (initialized) {
            return;
        }

        ensureDatabaseDirectoryExists();
        try {
            Class.forName(databaseDriver);
            try (Connection connection = DriverManager.getConnection(
                databaseUrl,
                databaseUsername,
                databasePassword);
                 Statement statement = connection.createStatement()) {
                statement.executeUpdate("""
                        CREATE TABLE IF NOT EXISTS user_accounts (
                            username VARCHAR(100) PRIMARY KEY,
                            password VARCHAR(255) NOT NULL,
                            role VARCHAR(20) NOT NULL
                        )
                        """);
                statement.executeUpdate("""
                        CREATE TABLE IF NOT EXISTS students (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(255) NOT NULL
                        )
                        """);
                statement.executeUpdate("""
                        CREATE TABLE IF NOT EXISTS teachers (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(255) NOT NULL
                        )
                        """);
                statement.executeUpdate("""
                        CREATE TABLE IF NOT EXISTS class_rooms (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(255) NOT NULL
                        )
                        """);
            }
            initialized = true;
        } catch (ClassNotFoundException exception) {
            throw new IllegalStateException("Unable to load database driver", exception);
        } catch (SQLException exception) {
            throw new IllegalStateException("Unable to initialize database schema", exception);
        }
    }

    private void ensureDatabaseDirectoryExists() {
        if (!databaseUrl.startsWith("jdbc:h2:file:")) {
            return;
        }

        String filePath = databaseUrl.substring("jdbc:h2:file:".length());
        int optionsStart = filePath.indexOf(';');
        if (optionsStart >= 0) {
            filePath = filePath.substring(0, optionsStart);
        }

        Path databaseFile = Paths.get(System.getProperty("user.dir"), filePath).normalize();
        Path parentDirectory = databaseFile.getParent();
        if (parentDirectory == null) {
            return;
        }

        try {
            Files.createDirectories(parentDirectory);
        } catch (IOException exception) {
            throw new IllegalStateException("Unable to create database directory " + parentDirectory, exception);
        }
    }
}